apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: gps-mcp-server
  namespace: gps-mcp-server
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: gps-mcp-server
  port:
    targetPort: http
